# NumPy N-dimensional Array

In [10]:
#create array
from numpy import array

In [5]:
#create array
l=[1.0,2.0,3.0]
a = array(l)

In [6]:
#display array
print(a)

[1. 2. 3.]


In [7]:
#display array shape
print(a.shape)

(3,)


In [8]:
#display array data type
print(a.dtype)

float64


# Functions to Create Arrays

<b>Empty:</b> The empty() function will create a new array of the specied shape. The argument to the function is an array or tuple that specifies the length of each dimension of the array to create. The values or content of the created array will be random and will need to be assigned before use. The example below creates an empty 3 x 3 two-dimensional array.

In [13]:
#create empty array
from numpy import empty
a = empty([3,3])
print(a)

[[1.28012640e-152 9.13616837e+242 1.38759998e+219]
 [2.46295242e+198 9.32223636e+218 2.17235218e-153]
 [2.64070768e-061 8.82069537e+199 5.49973442e+303]]


<b>Zeros:</b> The zeros() function will create a new array of the specied size with the contents filled with zero values. The argument to the function is an array or tuple that specifies the length of each dimension of the array to create. The example below creates a 3 x 5 zero two-dimensional array.

In [14]:
#create zeros array
from numpy import zeros
a = zeros([3,5])
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


<b>Ones:</b> The ones() function will create a new array of the specified size with the contents filled with
one values. The argument to the function is an array or tuple that specifies the length of each
dimension of the array to create. The example below creates a 5-element one-dimensional array.

In [16]:
#create ones array
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


# Combining Arrays

<b>Vertical Stack:</b> Given two or more existing arrays, you can stack them vertically using the vstack() function. For example,given two one-dimensional arrays, you can create a new two-dimensional array with two rows by vertically stacking them. This is demonstrated in the example below. 

In [18]:
# create array with vstack
from numpy import array
from numpy import vstack
#create first array
a1 = array([1,2,3])
print(a1)
#create second array
a2 = array([4,5,6])
print(a2)
#vertical stack
a3 = vstack((a1,a2))
print(a3)
print(a3.shape)


[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


<b>Horizontal Stack:</b> Given two or more existing arrays, you can stack them horizontally using the hstack() function. For example, given two one-dimensional arrays, you can create a new one-dimensional array or one row with the columns of the first and second arrays concatenated. This is demonstrated in the example below.

In [19]:
# create array with hstack
from numpy import array
from numpy import hstack
#create first array
a1 = array([1,2,3])
print(a1)
#create second array
a2 = array([4,5,6])
print(a2)
#vertical stack
a3 = hstack((a1,a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


# Extensions

This section lists some ideas for extending the tutorial that you may wish to explore.
<ul>
<li>Experiment with the different ways of creating arrays to your own sizes or with new data.</li>
<li>Locate and develop an example for 3 additional NumPy functions for creating arrays.</li>
<li>Locate and develop an example for 3 additional NumPy functions for combining arrays.</li>
</ul>

Additional NumPy functions for creating arrays.

<b>arange:</b> Like the built-in range but returns an ndarray instead of a list.

In [21]:
# create array with arange
from numpy import arange
a = arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


<b>eye or identity:</b> Create a square N x N identity matrix (1’s on the diagonal and 0’s elsewhere)

In [29]:
# create array with eye
from numpy import eye
a = eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [26]:
# create array with identity
from numpy import identity
a = identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


<b>dstack:</b> Stack arrays in sequence depth wise (along third axis). Takes a sequence of arrays and stack them along the third axis to make a single array. Rebuilds arrays divided by dsplit. This is a simple way to stack 2D arrays (images) into a single 3D array for processing.

In [30]:
# create array with dstack
from numpy import dstack
from numpy import array
#create first array
a1 = array([1,2,3])
print(a1)
#create second array
a2 = array([4,5,6])
print(a2)
#vertical stack
a3 = dstack((a1,a2))
print(a3)
print(a3.shape)


[1 2 3]
[4 5 6]
[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)


<b>concatenate:</b> Join a sequence of arrays along an existing axis.

In [32]:
# create array with dstack
from numpy import concatenate
from numpy import array
#create first array
a1 = array([[1, 2], [3, 4]])
print(a1)
#create second array
a2 = array([[5, 6]])
print(a2)
#vertical stack
a3 = concatenate((a1,a2))
print(a3)
print(a3.shape)

[[1 2]
 [3 4]]
[[5 6]]
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


<b>dsplit:</b> Split array into multiple sub-arrays along the 3rd axis (depth). Please refer to the split documentation. dsplit is equivalent to split with axis=2, the array is always split along the third axis provided the array dimension is greater than or equal to 3.

In [42]:
# create array with dstack
from numpy import dsplit
from numpy import array
from numpy import arange
x = arange(16.0).reshape(2, 2, 4)
print(x)
a1 = dsplit(x, 2)
print(a1)

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]
[array([[[ 0.,  1.],
        [ 4.,  5.]],

       [[ 8.,  9.],
        [12., 13.]]]), array([[[ 2.,  3.],
        [ 6.,  7.]],

       [[10., 11.],
        [14., 15.]]])]


In [39]:
a2 = dsplit(x, array([2, 4]))
print(a2)

[array([[[ 0.,  1.],
        [ 4.,  5.]],

       [[ 8.,  9.],
        [12., 13.]]]), array([[[ 2.,  3.],
        [ 6.,  7.]],

       [[10., 11.],
        [14., 15.]]]), array([], shape=(2, 2, 0), dtype=float64)]
