Vectors are a foundational element of linear algebra. Vectors are used throughout the field of machine learning in the description of algorithms and processes such as the target variable (y) when training an algorithm.

# 1. What is a Vector?

A vector is a tuple of one or more values called scalars. Vectors are often represented using a lowercase character such as v; for example:
\begin{equation*}
v =  (v_{1},  v_{2}, v_{3})
\end{equation*}
<br>
Where $v_{1}$,  $v_{2}$, $v_{3}$ are scalar values, often real values. <br>
Vectors are also shown using a vertical representation or a column; for example:<br>
\begin{equation*}
v = \begin{vmatrix}
v_{1}  \\
v_{2} \\
v_{3}
\end{vmatrix}
\end{equation*}
<br>
It is common to represent the target variable as a vector with the lowercase y when describing the training of a machine learning algorithm. It is common to introduce vectors using a geometric analogy, where a vector represents a point or coordinate in an n-dimensional space, where n is the number of dimensions, such as 2. The vector can also be thought of as a line from the
origin of the vector space with a direction and a magnitude.
<br>
These analogies are good as a starting point, but should not be held too tightly as we often consider very high dimensional vectors in machine learning. I find the vector-as-coordinate the most compelling analogy in machine learning. Now that we know what a vector is, let's look at how to define a vector in Python.

# 2. Defining a Vector

We can represent a vector in Python as a NumPy array. A NumPy array can be created from a list of numbers. For example, below we dene a vector with the length of 3 and the integer values 1, 2 and 3.

In [1]:
# create a vector
from numpy import array
# define vector
v = array([1, 2, 3])
print(v)

[1 2 3]


# 3. Vector Arithmetic

In this section will demonstrate simple vector-vector arithmetic, where all operations are performed element-wise between two vectors of equal length to result in a new vector with the same length

<b>Vector Addition:</b> Two vectors of equal length can be added together to create a new third vector.
\begin{equation*}
c = a + b
\end{equation*}
<br>
The new vector has the same length as the other two vectors. Each element of the new vector is calculated as the addition of the elements of the other vectors at the same index; for example:
\begin{equation*}
c = (a_{1} + b_{1}, a_{2} + b_{2}, a_{3} + b_{3})
\end{equation*}
<br>
Or, put another way:
\begin{equation*}
c[0] = a[0] + b[0] \\
c[1] = a[1] + b[1] \\
c[2] = a[2] + b[2]
\end{equation*}
<br>
We can add vectors directly in Python by adding NumPy arrays.

In [2]:
# vector addition
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# add vectors
c = a + b
print(c)

[1 2 3]
[1 2 3]
[2 4 6]


<b>Vector Subtraction:</b> One vector can be subtracted from another vector of equal length to create a new third vector.
\begin{equation*}
c = a - b
\end{equation*}
<br>
As with addition, the new vector has the same length as the parent vectors and each element of the new vector is calculated as the subtraction of the elements at the same indices.
\begin{equation*}
c = (a_{1} - b_{1}, a_{2} - b_{2}, a_{3} - b_{3})
\end{equation*}
<br>
Or, put another way:
\begin{equation*}
c[0] = a[0] - b[0] \\
c[1] = a[1] - b[1] \\
c[2] = a[2] - b[2]
\end{equation*}
<br>
The NumPy arrays can be directly subtracted in Python.

In [7]:
# vector subtraction
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([0.5, 0.5, 0.5])
print(b)
# subtract vectors
c = a - b
print(c)

[1 2 3]
[0.5 0.5 0.5]
[0.5 1.5 2.5]


<b>Vector Multiplication:</b> Two vectors of equal length can be multiplied together.
\begin{equation*}
c = a \times b
\end{equation*}
<br>
As with addition and subtraction, this operation is performed element-wise to result in a new vector of the same length.
\begin{equation*}
c = (a_{1} \times b_{1}, a_{2} \times b_{2}, a_{3} \times b_{3})
\end{equation*}
<br>
or
\begin{equation*}
c = (a_{1}b_{1}, a_{2}b_{2}, a_{3}b_{3})
\end{equation*}
Or, put another way:
\begin{equation*}
c[0] = a[0] \times b[0] \\
c[1] = a[1] \times b[1] \\
c[2] = a[2] \times b[2]
\end{equation*}
<br>
We can perform this operation directly in NumPy.

In [4]:
# vector multiplication
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a * b
print(c)

[1 2 3]
[1 2 3]
[1 4 9]


<b>Vector Division:</b> Two vectors of equal length can be divided.
\begin{equation*}
c = \frac{a}{b}
\end{equation*}
<br>
As with other arithmetic operations, this operation is performed element-wise to result in a new vector of the same length.
\begin{equation*}
c = (\frac{a_{1}}{b_{1}}, \frac{a_{2}}{b_{2}}, \frac{a_{3}}{b_{3}})
\end{equation*}
<br>
Or, put another way:
\begin{equation*}
c[0] = a[0] / b[0] \\
c[1] = a[1] / b[1] \\
c[2] = a[2] / b[2]
\end{equation*}
<br>
We can perform this operation directly in NumPy.

In [6]:
# vector division
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# divide vectors
c = a / b
print(c)

[1 2 3]
[1 2 3]
[1. 1. 1.]


<b>Vector Dot Product:</b> We can calculate the sum of the multiplied elements of two vectors of the same length to give a
scalar. This is called the dot product, named because of the dot operator used when describing the operation.
\begin{equation*}
c = a \cdot b
\end{equation*}
<br>
The operation can be used in machine learning to calculate the weighted sum of a vector. <br>
The dot product is calculated as follows:
\begin{equation*}
c = (a_{1} \times b_{1} + a_{2} \times b_{2} + a_{3} \times b_{3})
\end{equation*}
<br>
or \begin{equation*}
c = (a_{1}b_{1} + a_{2}b_{2} + a_{3}b_{3})
\end{equation*}
<br>
We can calculate the dot product between two vectors in Python using the *dot()* function on a NumPy array.

In [8]:
# vector dot product
from numpy import array
# define first vector
a = array([1, 2, 3])
print(a)
# define second vector
b = array([1, 2, 3])
print(b)
# multiply vectors
c = a.dot(b)
print(c)

[1 2 3]
[1 2 3]
14


<b>Vector-Scalar Multiplication:</b> A vector can be multiplied by a scalar, in effect scaling the magnitude of the vector. To keep notation simple, we will use lowercase s to represent the scalar value.
\begin{equation*}
c = s \times v
\end{equation*}
<br>
or \begin{equation*}
c = sv
\end{equation*}
The multiplication is performed on each element of the vector to result in a new scaled vector of the same length.
\begin{equation*}
c = (s \times v_{1}, s \times v_{2}, s \times v_{3})
\end{equation*}
<br>
Or, put another way: \begin{equation*}
c[0] = v[0] \times s \\
c[1] = v[1] \times s \\
c[2] = v[2] \times s
\end{equation*}
<br>
We can perform this operation directly with the NumPy array.

In [9]:
# vector-scalar multiplication
from numpy import array
# define vector
a = array([1, 2, 3])
print(a)
# define scalar
s = 0.5
print(s)
# multiplication
c = s * a
print(c)

[1 2 3]
0.5
[0.5 1.  1.5]


Similarly, vector-scalar addition, subtraction, and division can be performed in the same way.