Matrices are a foundational element of linear algebra. Matrices are used throughout the field of machine learning in the description of algorithms and processes such as the input data variable (X) when training an algorithm.

# 1. What is a Matrix?

A matrix is a two-dimensional array of scalars with one or more columns and one or more rows.
<br>
The notation for a matrix is often an uppercase letter, such as A, and entries are referred to by their two-dimensional subscript of row (i) and column (j), such as $a_{i,j}$ . For example, we can define a 3-row, 2-column matrix:
\begin{equation*}
A = ((a_{1,1},a_{1,2}), (a_{2,1},a_{2,2}) , (a_{3,1},a_{3,2}))
\end{equation*}
<br>
It is more common to see matrices defined using a horizontal notation.
\begin{equation*}
A =  \begin{vmatrix}
a_{1,1} & a_{1,2} \\
a_{2,1} &  a_{2,2} \\
a_{3,1} &  a_{3,2}
\end{vmatrix}
\end{equation*}
<br>
A likely first place you may encounter a matrix in machine learning is in model training data comprised of many rows and columns and often represented using the capital letter X. The geometric analogy used to help understand vectors and some of their operations does not hold with matrices. Further, a vector itself may be considered a matrix with one column and multiple rows. Often the dimensions of the matrix are denoted as m and n or $m \times n$ for the number of rows and the number of columns respectively.

# 2. Defining a Matrix

We can represent a matrix in Python using a two-dimensional NumPy array. A NumPy array can be constructed given a list of lists. For example, below is a 2 row, 3 column matrix.

In [1]:
# create matrix
from numpy import array
A = array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


# 3. Matrix Arithmetic

<b>Matrix Addition:</b> Two matrices with the same dimensions can be added together to create a new third matrix.
\begin{equation*}
C = A + B
\end{equation*}
<br>
The scalar elements in the resulting matrix are calculated as the addition of the elements in each of the matrices being added.
\begin{equation*}
C =  \begin{vmatrix}
a_{1,1} + b_{1,1} & a_{1,2} + b_{1,2}\\
a_{2,1} + b_{2,1} & a_{2,2} + b_{2,2} \\
a_{3,1} + b_{3,1} & a_{3,2} + b_{3,2}
\end{vmatrix}
\end{equation*}
<br>
or, put another way:
\begin{equation*}
C[0,0] = A[0,0] + B[0,0] \\
C[1,0] = A[1,0] + B[1,0] \\
C[2,0] = A[2,0] + B[2,0] \\
C[0,1] = A[0,1] + B[0,1] \\
C[1,1] = A[1,1] + B[1,1] \\
C[2,1] = A[2,1] + B[2,1]
\end{equation*}
<br>
We can implement this in Python using the plus operator directly on the two NumPy arrays.

In [2]:
# matrix addition
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# add matrices
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


<b>Matrix Subtraction:</b> Similarly, one matrix can be subtracted from another matrix with the same dimensions.
\begin{equation*}
C = A - B
\end{equation*}
<br>
The scalar elements in the resulting matrix are calculated as the subtraction of the elements in each of the matrices.
\begin{equation*}
C =  \begin{vmatrix}
a_{1,1} - b_{1,1} & a_{1,2} - b_{1,2}\\
a_{2,1} - b_{2,1} & a_{2,2} - b_{2,2} \\
a_{3,1} - b_{3,1} & a_{3,2} - b_{3,2}
\end{vmatrix}
\end{equation*}
<br>
or, put another way:
\begin{equation*}
C[0,0] = A[0,0] - B[0,0] \\
C[1,0] = A[1,0] - B[1,0] \\
C[2,0] = A[2,0] - B[2,0] \\
C[0,1] = A[0,1] - B[0,1] \\
C[1,1] = A[1,1] - B[1,1] \\
C[2,1] = A[2,1] - B[2,1]
\end{equation*}
<br>
We can implement this in Python using the minus operator directly on the two NumPy arrays.

In [3]:
# matrix subtraction
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[0.5, 0.5, 0.5],
[0.5, 0.5, 0.5]])
print(B)
# subtract matrices
C = A - B
print(C)

[[1 2 3]
 [4 5 6]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


<b>Matrix Multiplication (Hadamard Product):</b> Two matrices with the same size can be multiplied together, and this is often called element-wise matrix multiplication or the Hadamard product. It is not the typical operation meant when referring to matrix multiplication, therefore a different operator is often used, such as a circle $\circ$.
\begin{equation*}
C = A \circ B
\end{equation*}
<br>
As with element-wise subtraction and addition, element-wise multiplication involves the multiplication of elements from each parent matrix to calculate the values in the new matrix.
\begin{equation*}
C =  \begin{vmatrix}
a_{1,1} \times b_{1,1} & a_{1,2} \times b_{1,2}\\
a_{2,1} \times b_{2,1} & a_{2,2} \times b_{2,2} \\
a_{3,1} \times b_{3,1} & a_{3,2} \times b_{3,2}
\end{vmatrix}
\end{equation*}
<br>
or, put another way:
\begin{equation*}
C[0,0] = A[0,0] \times B[0,0] \\
C[1,0] = A[1,0] \times B[1,0] \\
C[2,0] = A[2,0] \times B[2,0] \\
C[0,1] = A[0,1] \times B[0,1] \\
C[1,1] = A[1,1] \times B[1,1] \\
C[2,1] = A[2,1] \times B[2,1]
\end{equation*}
<br>
We can implement this in Python using the star operator directly on the two NumPy arrays.

In [4]:
# matrix Hadamard product
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# multiply matrices
C = A * B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


<b>Matrix Division:</b> One matrix can be divided by another matrix with the same dimensions.
\begin{equation*}
C = \frac{A}{B}
\end{equation*}
<br>
As with element-wise subtraction and addition, element-wise multiplication involves the multiplication of elements from each parent matrix to calculate the values in the new matrix.
\begin{equation*}
C =  \begin{vmatrix}
\frac{a_{1,1}}{b_{1,1}} & \frac{a_{1,2}}{b_{1,2}}\\
\frac{a_{2,1}}{b_{2,1}} & \frac{a_{2,2}}{b_{2,2}} \\
\frac{a_{3,1}}{b_{3,1}} & \frac{a_{3,2}}{b_{3,2}}
\end{vmatrix}
\end{equation*}
<br>
or, put another way:
\begin{equation*}
C[0,0] = A[0,0] / B[0,0] \\
C[1,0] = A[1,0] / B[1,0] \\
C[2,0] = A[2,0] / B[2,0] \\
C[0,1] = A[0,1] / B[0,1] \\
C[1,1] = A[1,1] / B[1,1] \\
C[2,1] = A[2,1] / B[2,1]
\end{equation*}
<br>
We can implement this in Python using the division operator directly on the two NumPy arrays.

In [5]:
# matrix division
from numpy import array
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# divide matrices
C = A / B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


<b>Matrix-Matrix Multiplication:</b> Matrix multiplication, also called the matrix dot product is more complicated than the previous operations and involves a rule as not all matrices can be multiplied together.
\begin{equation*}
C = A \cdot B
\end{equation*}
<br>
or, 
\begin{equation*}
C = AB
\end{equation*}
<br>
The rule for matrix multiplication is as follows:
* The number of columns (n) in the first matrix (A) must equal the number of rows (m) in the second matrix (B).
<br><br>
For example, matrix A has the dimensions m rows and n columns and matrix B has the dimensions n and k. The n columns in A and n rows in B are equal. The result is a new matrix with m rows and k columns.
\begin{equation*}
C(m,k) = A (m,n) \cdot B(n,k)
\end{equation*}
<br>
This rule applies for a chain of matrix multiplications where the number of columns in one matrix in the chain must match the number of rows in the following matrix in the chain.
<br>
The intuition for the matrix multiplication is that we are calculating the dot product between each row in matrix A with each column in matrix B. For example, we can step down rows of column A and multiply each with column 1 in B to give the scalar values in column 1 of C. Below describes the matrix multiplication using matrix notation.
\begin{equation*}
A =  \begin{vmatrix}
a_{1,1} & a_{1,2}\\
a_{2,1} & a_{2,2} \\
a_{3,1} & a_{3,2}
\end{vmatrix}
\end{equation*}
<br>
\begin{equation*}
B =  \begin{vmatrix}
b_{1,1} & b_{1,2}\\
b_{2,1} & b_{2,2} 
\end{vmatrix}
\end{equation*}
<br>
\begin{equation*}
C =  \begin{vmatrix}
a_{1,1} \times b_{1,1} + a_{1,2} \times b_{2,1} & a_{1,1} \times b_{1,2} + a_{1,2} \times b_{2,2}\\
a_{2,1} \times b_{1,1} + a_{2,2} \times b_{2,1} & a_{2,1} \times b_{1,2} + a_{2,2} \times b_{2,2}\\
a_{3,1} \times b_{1,1} + a_{3,2} \times b_{2,1} & a_{3,1} \times b_{1,2} + a_{3,2} \times b_{2,2}
\end{vmatrix}
\end{equation*}
<br>
We can describe the matrix multiplication operation using array notation.
\begin{equation*}
C[0,0] = A[0,0] \times B[0,0] +  A[0,1] \times B[1,0]\\
C[1,0] = A[1,0] \times B[0,0] +  A[1,1] \times B[1,0]\\
C[2,0] = A[2,0] \times B[0,0] +  A[2,1] \times B[1,0]\\
C[0,1] = A[0,0] \times B[0,1] +  A[0,1] \times B[1,1]\\
C[1,1] = A[1,0] \times B[0,1] +  A[1,1] \times B[1,1]\\
C[2,1] = A[2,0] \times B[0,1] +  A[2,1] \times B[1,1]\\
\end{equation*}
<br>
The matrix multiplication operation can be implemented in NumPy using the *dot()* function. It can also be calculated using the newer @ operator, since Python version 3.5. The example below demonstrates both methods.

In [6]:
# matrix dot product
from numpy import array
# define first matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define second matrix
B = array([
[1, 2],
[3, 4]])
print(B)
# multiply matrices
C = A.dot(B)
print(C)
# multiply matrices with @ operator
D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]


<b>Matrix-Vector Multiplication:</b> A matrix and a vector can be multiplied together as long as the rule of matrix multiplication is observed. Specifically, that the number of columns in the matrix must equal the number of items in the vector. As with matrix multiplication, the operation can be written using the dot notation. Because the vector only has one column, the result is always a vector.
<br>
\begin{equation*}
C = A \cdot v
\end{equation*}
<br>
or, 
\begin{equation*}
C = Av
\end{equation*}
<br>
The result is a vector with the same number of rows as the parent matrix.
\begin{equation*}
A =  \begin{vmatrix}
a_{1,1} & a_{1,2}\\
a_{2,1} & a_{2,2} \\
a_{3,1} & a_{3,2}
\end{vmatrix}
\end{equation*}
<br>
\begin{equation*}
v =  \begin{vmatrix}
v_{1} \\
v_{2} 
\end{vmatrix}
\end{equation*}
<br>
\begin{equation*}
C =  \begin{vmatrix}
a_{1,1} \times v_{1} +  a_{1,2} \times v_{2}\\
a_{2,1} \times v_{1} +  a_{2,2} \times v_{2}\\
a_{3,1} \times v_{1} +  a_{3,2} \times v_{2}
\end{vmatrix}
\end{equation*}
<br>
Or, more compactly.
\begin{equation*}
c =  \begin{vmatrix}
a_{1,1}v_{1} +  a_{1,2}v_{2}\\
a_{2,1}v_{1} +  a_{2,2}v_{2}\\
a_{3,1}v_{1} +  a_{3,2}v_{2}
\end{vmatrix}
\end{equation*}
<br>
We can also represent this with array notation.
\begin{equation*}
c[0] = A[0,0] \times v[0] +  A[0,1] \times v[1]\\
c[1] = A[1,0] \times v[0] +  A[1,1] \times v[1]\\
c[2] = A[2,0] \times v[0] +  A[2,1] \times v[1]
\end{equation*}
<br>
The matrix-vector multiplication can be implemented in NumPy using the *dot()* function.

In [ ]:
# matrix-vector multiplication
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define vector
B = array([0.5, 0.5])
print(B)
# multiply
C = A.dot(B)
print(C)

<b>Matrix-Scaler Multiplication:</b> A matrix can be multiplied by a scalar. This can be represented using the dot notation between the matrix and the scalar.
<br>
\begin{equation*}
C = A \cdot b
\end{equation*}
<br>
Or without the dot notation.
\begin{equation*}
C = Ab
\end{equation*}
<br>
The result is a matrix with the same size as the parent matrix where each element of the matrix is multiplied by the scalar value.
\begin{equation*}
A =  \begin{vmatrix}
a_{1,1} & a_{1,2}\\
a_{2,1} & a_{2,2} \\
a_{3,1} & a_{3,2}
\end{vmatrix}
\end{equation*}
<br>
\begin{equation*}
C =  \begin{vmatrix}
a_{1,1} \times b +  a_{1,2} \times b\\
a_{2,1} \times b +  a_{2,2} \times b\\
a_{3,1} \times b +  a_{3,2} \times b
\end{vmatrix}
\end{equation*}
<br>
Or, more compactly.
\begin{equation*}
c =  \begin{vmatrix}
a_{1,1}b +  a_{1,2}b\\
a_{2,1}b +  a_{2,2}b\\
a_{3,1}b +  a_{3,2}b
\end{vmatrix}
\end{equation*}
<br>
We can also represent this with array notation.
\begin{equation*}
C[0,0] = A[0,0] \times b\\
C[1,0] = A[1,0] \times b\\
C[2,0] = A[2,0] \times b\\
C[0,1] = A[0,0] \times b\\
C[1,1] = A[1,0] \times b\\
C[2,1] = A[2,0] \times b\\
\end{equation*}
<br>
This can be implemented directly in NumPy with the multiplication operator.

In [8]:
# matrix-scalar multiplication
from numpy import array
# define matrix
A = array([[1, 2], [3, 4], [5, 6]])
print(A)
# define scalar
b = 0.5
print(b)
# multiply
C = A * b
print(C)

[[1 2]
 [3 4]
 [5 6]]
0.5
[[0.5 1. ]
 [1.5 2. ]
 [2.5 3. ]]
