# Types of Matrices

# 1. Square Matrix

A lot of linear algebra is concerned with operations on vectors and matrices, and there are many different types of matrices. There are a few types of matrices that you may encounter again and again when getting started in linear algebra, particularity the parts of linear algebra relevant to machine learning.

A square matrix is a matrix where the number of rows ($n$) is equivalent to the number of columns ($m$).
\begin{equation*}
n \equiv m
\end{equation*}

The square matrix is contrasted with the rectangular matrix where the number of rows and columns are not equal. Given that the number of rows and columns match, the dimensions are usually denoted as $n$, e.g. $n x n$. The size of the matrix is called the order, so an order $4$ square matrix is $4 x 4$. The vector of values along the diagonal of the matrix from the top left to the
bottom right is called the main diagonal. Below is an example of an order 3 square matrix.
<br>
\begin{equation*}
M=  \begin{vmatrix}
1 & 2 & 3 \\
1 & 2 & 3 \\
1 & 2 & 3 
\end{vmatrix}
\end{equation*}
Square matrices are readily added and multiplied together and are the basis of many simple linear transformations, such as rotations (as in the rotations of images).

# 2. Symmetric Matrix

A symmetric matrix is a type of square matrix where the top-right triangle is the same as the bottom-left triangle. To be symmetric, the axis of symmetry is always the main diagonal of the matrix, from the top left to the bottom right. Below is an example of a $5 x 5$ symmetric matrix.
<br>
\begin{equation*}
M=  \begin{vmatrix}
1 & 2 & 3 & 4 & 5\\
2 & 1 & 2 & 3 & 4\\
3 & 2 & 1 & 2 & 3\\
4 & 3 & 2 & 1 & 2\\
5 & 4 & 3 & 2 & 1\\
\end{vmatrix}
\end{equation*}
<br>
A symmetric matrix is always square and equal to its own transpose. The transpose is an operation that  flips the number of rows and columns. It is explained in more detail in the next lesson.
<br>
\begin{equation*}
M = M^{T}  
\end{equation*}

# 3. Triangular Matrix

A triangular matrix is a type of square matrix that has all values in the upper-right or lower-left of the matrix with the remaining elements filled with zero values. A triangular matrix with values only above the main diagonal is called an upper triangular matrix. Whereas, a triangular matrix with values only below the main diagonal is called a lower triangular matrix. Below is an example of a 3 x 3 upper triangular matrix.
<br>
\begin{equation*}
M=  \begin{vmatrix}
1 & 2 & 3 \\
0 & 2 & 3 \\
0 & 0 & 3 
\end{vmatrix}
\end{equation*}
<br>
Below is an example of a 3 x 3 lower triangular matrix.
<br>
\begin{equation*}
M=  \begin{vmatrix}
1 & 0 & 0 \\
1 & 2 & 0 \\
1 & 2 & 3 
\end{vmatrix}
\end{equation*}
<br>
NumPy provides functions to calculate a triangular matrix from an existing square matrix. The tril() function to calculate the lower triangular matrix from a given matrix and the triu() to calculate the upper triangular matrix from a given matrix The example below defines a 3 x 3 square matrix and calculates the lower and upper triangular matrix from it.

In [1]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# lower triangular matrix
lower = tril(M)
print(lower)
# upper triangular matrix
upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


# 4. Diagonal Matrix

A diagonal matrix is one where values outside of the main diagonal have a zero value, where the main diagonal is taken from the top left of the matrix to the bottom right. A diagonal matrix is often denoted with the variable D and may be represented as a full matrix or as a vector of values on the main diagonal.
<br>
Below is an example of a 3 x 3 square diagonal matrix.
<br>
\begin{equation*}
D =  \begin{vmatrix}
1 & 0 & 0 \\
0 & 2 & 0 \\
0 & 0 & 3 
\end{vmatrix}
\end{equation*}
<br>
As a vector, it would be represented as:
<br>
\begin{equation*}
d =  \begin{vmatrix}
d_{1,1} \\
d_{2,2} \\
d_{3,3}
\end{vmatrix}
\end{equation*}
<br>
A diagonal matrix does not have to be square. In the case of a rectangular matrix, the diagonal would cover the dimension with the smallest length; for example:
<br>
\begin{equation*}
D =  \begin{vmatrix}
1 & 0 & 0 & 0\\
0 & 2 & 0 & 0\\
0 & 0 & 3 & 0\\
0 & 0 & 0 & 4\\
0 & 0 & 0 & 0
\end{vmatrix}
\end{equation*}
<br>
NumPy provides the function diag() that can create a diagonal matrix from an existing matrix, or transform a vector into a diagonal matrix. The example below defines a 3 x 3 square matrix, extracts the main diagonal as a vector, and then creates a diagonal matrix from the extracted vector.

In [2]:
# diagonal matrix
from numpy import array
from numpy import diag
# define square matrix
M = array([
[1, 2, 3],
[1, 2, 3],
[1, 2, 3]])
print(M)
# extract diagonal vector
d = diag(M)
print(d)
# create diagonal matrix from vector
D = diag(d)
print(D)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


# 5. Identity Matrix

An identity matrix is a square matrix that does not change a vector when multiplied. The values of an identity matrix are known. All of the scalar values along the main diagonal (top-left to bottom-right) have the value one, while all other values are zero.
<br>
An identity matrix is often represented using the notation I or with the dimensionality $I^n$, where n is a subscript that indicates the dimensionality of the square identity matrix. In some notations, the identity may be referred to as the unit matrix, or $U$, to honor the one value it contains (this is different from a Unitary matrix). For example, an identity matrix with the size $3$ or $I^3$ would be as follows:

<br>
\begin{equation*}
I =  \begin{vmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1 
\end{vmatrix}
\end{equation*}
<br>
In NumPy, an identity matrix can be created with a specific size using the identity() function. The example below creates an I3 identity matrix.

In [3]:
# identity matrix
from numpy import identity
I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 6. Orthogonal Matrix

Two vectors are orthogonal when their dot product equals zero. The length of each vector is 1 then the vectors are called orthonormal because they are both orthogonal and normalized. 
<br>
\begin{equation*}
v \cdot w = 0
\end{equation*}
<br>
or
<br>
\begin{equation*}
v \cdot w^{T} = 0
\end{equation*}
<br>
This is intuitive when we consider that one line is orthogonal with another if it is perpendicular to it. An orthogonal matrix is a type of square matrix whose columns and rows are orthonormal unit vectors, e.g. perpendicular and have a length or magnitude of 1.
<br>
An orthogonal matrix is a square matrix whose rows are mutually orthonormal and whose columns are mutually orthonormal
<br>
An Orthogonal matrix is often denoted as uppercase Q.
<br>
The Orthogonal matrix is defined formally as follows:
<br>
\begin{equation*}
Q^{T} \cdot Q =  Q \cdot Q^{T} = I
\end{equation*}
<br>
Where Q is the orthogonal matrix, QT indicates the transpose of Q, and I is the identity matrix. A matrix is orthogonal if its transpose is equal to its inverse.
<br>
\begin{equation*}
Q^{T} = Q^{-1} 
\end{equation*}
<br>
Another equivalence for an orthogonal matrix is if the dot product of the matrix and itself equals the identity matrix.
<br>
\begin{equation*}
 Q \cdot Q^{T} = I
\end{equation*}
<br>
Orthogonal matrices are used a lot for linear transformations, such as reflections and permutations. A simple 2 x 2 orthogonal matrix is listed below, which is an example of a reflection matrix or coordinate reflection.
<br>
\begin{equation*}
Q =  \begin{vmatrix}
1 & 0  \\
0 & -1  
\end{vmatrix}
\end{equation*}
<br>
