Matrix operations are used in the description of many machine learning algorithms. Some operations can be used directly to solve key equations, whereas others provide useful shorthand or foundation in the description and the use of more complex matrix operations.

# 1. Transpose

A defined matrix can be transposed, which creates a new matrix with the number of columns and rows  flipped. This is denoted by the superscript T next to the matrix $A^T$.
<br>
\begin{equation*}
C = A^{T}
\end{equation*}
<br>
An invisible diagonal line can be drawn through the matrix from top left to bottom right on which the matrix can be 
flipped to give the transpose.
<br>
\begin{equation*}
A =  \begin{vmatrix}
1 & 2 \\
3 & 4 \\
5 & 6 
\end{vmatrix}
\end{equation*}
<br>
\begin{equation*}
A^{T} =  \begin{vmatrix}
1 & 3 & 5\\
2 & 4 & 6\\
\end{vmatrix}
\end{equation*}
<br>
The operation has no effect if the matrix is symmetrical, e.g. has the same number of columns and rows and the same values at the same locations on both sides of the invisible diagonal line.
<br>
We can transpose a matrix in NumPy by calling the T attribute.

In [1]:
# transpose matrix
from numpy import array
# define matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# calculate transpose
C = A.T
print(C)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


# 2. Inverse

Matrix inversion is a process that finds another matrix that when multiplied with the matrix, results in an identity matrix. Given a matrix A, find matrix B, such that AB = $I^{n}$ or BA = $I^{n}$.
<br>
\begin{equation*}
AB = BA = I^{n}
\end{equation*}
<br>
The operation of inverting a matrix is indicated by a $-1$ superscript next to the matrix; for example, $A^{-1}$. The result of the operation is referred to as the inverse of the original matrix; for example, B is the inverse of A.
<br>
\begin{equation*}
B = A^{-1}
\end{equation*}
<br>
A matrix is invertible if there exists another matrix that results in the identity matrix, where not all matrices are invertible. A square matrix that is not invertible is referred to as singular.
<br>
The matrix inversion operation is not computed directly, but rather the inverted matrix is discovered through a numerical operation, where a suite of efficient methods may be used, often involving forms of matrix decomposition.
<br>
A matrix can be inverted in NumPy using the inv() function.

In [2]:
# invert matrix
from numpy import array
from numpy.linalg import inv
# define matrix
A = array([
[1.0, 2.0],
[3.0, 4.0]])
print(A)
# invert matrix
B = inv(A)
print(B)
# multiply A and B
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


# 3. Trace

A trace of a square matrix is the sum of the values on the main diagonal of the matrix (top-left to bottom-right). The operation of calculating a trace on a square matrix is described using the notation *tr(A)* ehere A is the square matrix on which the operation is being performed.
<br>
\begin{equation*}
tr(A)
\end{equation*}
<br>
The trace is calculated as the sum of the diagonal values; for example, in the case of a 3 x 3 matrix:
<br>
\begin{equation*}
tr(A) = a_{1,1} + a_{2,2} + a_{3,3}
\end{equation*}
<br>
Or, using array notation:
<br>
\begin{equation*}
tr(A) = A[0,0] + A[1,1] + A[2,2]
\end{equation*}
<br>
We can calculate the trace of a matrix in NumPy using the trace() function.

In [3]:
# matrix trace
from numpy import array
from numpy import trace
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# calculate trace
B = trace(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


# 4. Determinant

The determinant of a square matrix is a scalar representation of the volume of the matrix.
<br>
It is denoted by the det(A) notation or $|A|$, where A is the matrix on which we are calculating the determinant.
<br>
\begin{equation*}
det(A)
\end{equation*}
<br>
The determinant of a square matrix is calculated from the elements of the matrix. More technically, the determinant is the product of all the eigenvalues of the matrix. Eigenvalues are introduced in the lessons on matrix factorization. The intuition for the determinant is that it describes the way a matrix will scale another matrix when they are multiplied together. For example, a determinant of 1 preserves the space of the other matrix. A determinant of 0 indicates that the matrix cannot be inverted.
<br>
In NumPy, the determinant of a matrix can be calculated using the det() function.

In [4]:
# matrix determinant
from numpy import array
from numpy.linalg import det
# define matrix
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(A)
# calculate determinant
B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
0.0


# 5. Rank

The rank of a matrix is the estimate of the number of linearly independent rows or columns in a matrix. The rank of a matrix M is often denoted as the function rank().
<br>
\begin{equation*}
rank(A)
\end{equation*}
<br>
An intuition for rank is to consider it the number of dimensions spanned by all of the vectors within a matrix. For example, a rank of 0 suggest all vectors span a point, a rank of 1 suggests all vectors span a line, a rank of 2 suggests all vectors span a two-dimensional plane. The rank is estimated numerically, often using a matrix decomposition method. A common approach is to
use the Singular-Value Decomposition or SVD for short. NumPy provides the matrix rank() function for calculating the rank of an array. It uses the SVD method to estimate the rank. The example below demonstrates calculating the rank of a matrix with scalar values and another vector with all zero values.

In [5]:
# vector rank
from numpy import array
from numpy.linalg import matrix_rank
# rank
v1 = array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)
# zero rank
v2 = array([0,0,0,0,0])
print(v2)
vr2 = matrix_rank(v2)
print(vr2)

[1 2 3]
1
[0 0 0 0 0]
0


The next example makes it clear that the rank is not the number of dimensions of the matrix, but the number of linearly independent directions. Three examples of a 2 x 2 matrix are provided demonstrating matrices with rank 0, 1 and 2.

In [6]:
# matrix rank
from numpy import array
from numpy.linalg import matrix_rank
# rank 0
M0 = array([
[0,0],
[0,0]])
print(M0)
mr0 = matrix_rank(M0)
print(mr0)
# rank 1
M1 = array([
[1,2],
[1,2]])
print(M1)
mr1 = matrix_rank(M1)
print(mr1)
# rank 2
M2 = array([
[1,2],
[3,4]])
print(M2)
mr2 = matrix_rank(M2)
print(mr2)

[[0 0]
 [0 0]]
0
[[1 2]
 [1 2]]
1
[[1 2]
 [3 4]]
2
