Fundamental statistics are useful tools in applied machine learning for a better understanding your data. They are also the tools that provide the foundation for more advanced linear algebra operations and machine learning methods, such as the covariance matrix and principal component analysis respectively. As such, it is important to have a strong grip on fundamental statistics in the context of linear algebra notation.

# 1. Expected Value and Mean

In probability, the average value of some random variable $X$ is called the expected value or the expectation. The expected value uses the notation $E$ with square brackets around the name of the variable; for example:
<br><br>
\begin{equation*}
E[X]
\end{equation*}
<br><br>
It is calculated as the probability weighted sum of values that can be drawn.
<br><br>
\begin{equation*}
E[X] = \sum{x_{1} \times p_{1}, x_{2} \times p_{2}, x_{3} \times p_{3}, \cdots , x_{n} \times p_{n}}
\end{equation*}
<br><br>
In simple cases, such as the  flipping of a coin or rolling a dice, the probability of each event is just as likely. Therefore, the expected value can be calculated as the sum of all values multiplied by the reciprocal of the number of values.
<br><br>
\begin{equation*}
E[X] = \frac{1}{n} \times \sum{x_{1}, x_{2}, x_{3}, \cdots , x_{n}}
\end{equation*}
<br><br>
In statistics, the mean, or more technically the arithmetic mean or sample mean, can be estimated from a sample of examples drawn from the domain. It is confusing because mean, average, and expected value are used interchangeably. In the abstract, the mean is denoted by the lower case Greek letter mu $\mu$ and is calculated from the sample of observations, rather than all possible values.
<br><br>
\begin{equation*}
\mu = \frac{1}{n} \times \sum{x_{1}, x_{2}, x_{3}, \cdots , x_{n}}
\end{equation*}
<br><br>
Or, written more compactly:
<br><br>
\begin{equation*}
\mu = P(x) \times \sum{x}
\end{equation*}
<br><br>
Where $x$ is the vector of observations and $P(x)$ is the calculated probability for each value. When calculated for a specific variable, such as $x$, the mean is denoted as a lower case variable name with a line above, called x-bar e.g. $\bar{x}$.
<br><br>
\begin{equation*}
\bar{x} = \frac{1}{n} \times \sum^{n}_{i=1} {x_{i}}
\end{equation*}
<br><br>
The arithmetic mean can be calculated for a vector or matrix in NumPy by using the $mean()$ function. The example below defines a 6-element vector and calculates the mean.

In [1]:
# vector mean
from numpy import array
from numpy import mean
# define vector
v = array([1,2,3,4,5,6])
print(v)
# calculate mean
result = mean(v)
print(result)

[1 2 3 4 5 6]
3.5


The mean function can calculate the row or column means of a matrix by specifying the axis argument and the value 0 or 1 respectively. The example below defines a $2 \times 6$ matrix and calculates both column and row means.

In [2]:
# matrix means
from numpy import array
from numpy import mean
# define matrix
M = array([
[1,2,3,4,5,6],
[1,2,3,4,5,6]])
print(M)
# column means
col_mean = mean(M, axis=0)
print(col_mean)
# row means
row_mean = mean(M, axis=1)
print(row_mean)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[1. 2. 3. 4. 5. 6.]
[3.5 3.5]


# 2. Variance and Standard Deviation

In probability, the variance of some random variable X is a measure of how much values in the distribution vary on average with respect to the mean. The variance is denoted as the function $Var()$ on the variable.
<br><br>
\begin{equation*}
Var[X]
\end{equation*}
<br><br>
Variance is calculated as the average squared difference of each value in the distribution from the expected value. Or the expected squared difference from the expected value.
<br><br>
\begin{equation*}
Var[X] = E[(X-E[X])^{2}]
\end{equation*}
<br><br>
Assuming the expected value of the variable has been calculated ($E[X]$), the variance of the random variable can be calculated as the sum of the squared difference of each example from the expected value multiplied by the probability of that value.
<br><br>
\begin{equation*}
Var[X] = \sum{p(x_{1}) \times (x_{1}-E[X])^{2}, p(x_{2}) \times (x_{2}-E[X])^{2}, \cdots , p(x_{n}) \times (x_{n}-E[X])^{2}}
\end{equation*}
<br><br>
If the probability of each example in the distribution is equal, variance calculation can drop the individual probabilities and multiply the sum of squared differences by the reciprocal of the number of examples in the distribution.
<br><br>
\begin{equation*}
Var[X] = \frac{1}{n} \times \sum{(x_{1}-E[X])^{2}, (x_{2}-E[X])^{2}, \cdots , (x_{n}-E[X])^{2}}
\end{equation*}
<br><br>
In statistics, the variance can be estimated from a sample of examples drawn from the domain. In the abstract, the sample variance is denoted by the lower case sigma with a 2 superscript indicating the units are squared (e.g. $\sigma^{2}$), not that you must square the final value. The sum of the squared differences is multiplied by the reciprocal of the number of examples minus 1 to correct for a bias (bias is related to a deeper discussion on degrees of freedom).
<br><br>
\begin{equation*}
\sigma^{2} = \frac{1}{n-1} \times \sum_{i=1}^{n} {(x_{i}-\mu)^{2}}
\end{equation*}
<br><br>
In NumPy, the variance can be calculated for a vector or a matrix using the var() function. By default, the var() function calculates the population variance. To calculate the sample variance, you must set the ddof argument to the value 1. The example below defines a 6-element vector and calculates the sample variance.

In [1]:
# vector variance
from numpy import array
from numpy import var
# define vector
v = array([1,2,3,4,5,6])
print(v)
# calculate variance
result = var(v, ddof=1)
print(result)

[1 2 3 4 5 6]
3.5


The var function can calculate the row or column variances of a matrix by specifying the axis argument and the value $0$ or $1$ respectively, the same as the mean function above. The example below defines a $2 \times 6$ matrix and calculates both column and row sample variances.

In [2]:
# matrix variances
from numpy import array
from numpy import var
# define matrix
M = array([
[1,2,3,4,5,6],
[1,2,3,4,5,6]])
print(M)
# column variances
col_var = var(M, ddof=1, axis=0)
print(col_var)
# row variances
row_var = var(M, ddof=1, axis=1)
print(row_var)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[0. 0. 0. 0. 0. 0.]
[3.5 3.5]


The standard deviation is calculated as the square root of the variance and is denoted as lowercase $s$.
<br><br>
\begin{equation*}
s = \sqrt{\sigma^{2}}
\end{equation*}
<br><br>
To keep with this notation, sometimes the variance is indicated as $s^{2}$, with $2$ as a superscript, again showing that the units are squared. NumPy also provides a function for calculating the standard deviation directly via the $std()$ function. As with the $var()$ function, the ddof argument must be set to 1 to calculate the unbiased sample standard deviation and column and row standard deviations can be calculated by setting the axis argument to $0$ and $1$ respectively. The example below demonstrates how to calculate the sample standard deviation for the rows and columns of a matrix.

In [3]:
# matrix standard deviation
from numpy import array
from numpy import std
# define matrix
M = array([
[1,2,3,4,5,6],
[1,2,3,4,5,6]])
print(M)
# column standard deviations
col_std = std(M, ddof=1, axis=0)
print(col_std)
# row standard deviations
row_std = std(M, ddof=1, axis=1)
print(row_std)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
[0. 0. 0. 0. 0. 0.]
[1.87082869 1.87082869]


# 3. Covariance and Correlation

In probability, covariance is the measure of the joint probability for two random variables. It describes how the two variables change together. It is denoted as the function $cov(X,Y)$, where $X$ and $Y$ are the two random variables being considered.
<br><br>
\begin{equation*}
cov(X,Y)
\end{equation*}
<br><br>
Covariance is calculated as expected value or average of the product of the differences of each random variable from their expected values, where $E[X]$ is the expected value for $X$ and $E[Y]$ is the expected value of $y$.
<br><br>
\begin{equation*}
cov(X,Y) = E[(X-E[X]) \times (Y-E[Y])]
\end{equation*}
<br><br>
Assuming the expected values for X and Y have been calculated, the covariance can be calculated as the sum of the dierence of x values from their expected value multiplied by the difference of the y values from their expected values multiplied by the reciprocal of the number of examples in the population.
<br><br>
\begin{equation*}
cov(X,Y) = \frac{1}{n} \times \sum {(x-E[X]) \times (y-E[Y])}
\end{equation*}
<br><br>
In statistics, the sample covariance can be calculated in the same way, although with a bias correction, the same as with the variance.
<br><br>
\begin{equation*}
cov(X,Y) = \frac{1}{n-1} \times \sum {(x-E[X]) \times (y-E[Y])}
\end{equation*}
<br><br>
* The sign of the covariance can be interpreted as whether the two variables increase together (positive) or decrease together (negative). The magnitude of the covariance is not easily interpreted. 
* A covariance value of zero indicates that both variables are completely independent. 
* NumPy does not have a function to calculate the covariance between two variables directly.
* Instead, it has a function for calculating a covariance matrix called $cov()$ that we can use to retrieve the covariance. 
* By default, the $cov()$ function will calculate the unbiased or sample covariance between the provided random variables.
<br><br>
The example below defines two vectors of equal length with one increasing and one decreasing. We would expect the covariance between these variables to be negative. We access just the covariance for the two variables as the $[0,1]$ element of the square covariance matrix returned.

In [6]:
# vector covariance
from numpy import array
from numpy import cov
# define first vector
x = array([1,2,3,4,5,6,7,8,9])
print(x)
# define second covariance
y = array([9,8,7,6,5,4,3,2,1])
print(y)
# calculate covariance
Sigma = cov(x,y)[0,1]
print(Sigma)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
-7.5


The covariance can be normalized to a score between -1 and 1 to make the magnitude interpretable by dividing it by the standard deviation of X and Y . The result is called the correlation of the variables, also called the Pearson correlation coefficient, named for the developer of the method.
<br><br>
\begin{equation*}
r = \frac{cov(X,Y)}{s_{X} \times s_{Y}}
\end{equation*}
<br><br>
* Where $r$ is the correlation coefficient of $X$ and $Y$ , $cov(X,Y)$ is the sample covariance of $X$ and $Y$ and $s_{X}$ and $s_{Y}$ are the standard deviations of $X$ and $Y$ respectively. 
* NumPy provides the $corrcoef()$ function for calculating the correlation between two variables directly. Like $cov()$, it returns a matrix, in this case a correlation matrix. 
* As with the results from $cov()$ we can access just the correlation of interest from the $[0,1]$ value from the returned squared matrix.

In [12]:
# vector correlation
from numpy import array
from numpy import corrcoef
# define first vector
x = array([1,2,3,4,5,6,7,8,9])
print(x)
# define second vector
y = array([9,8,7,6,5,4,3,2,1])
print(y)
# calculate correlation
corr = corrcoef(x,y)[0,1]
print(corr)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]
-1.0


# 4. Covariance Matrix

* The covariance matrix is a square and symmetric matrix that describes the covariance between two or more random variables.
* The diagonal of the covariance matrix are the variances of each of the random variables, as such it is often called the variance-covariance matrix.
* A covariance matrix is a generalization of the covariance of two variables and captures the way in which all variables in the dataset may change together.
* The covariance matrix is denoted as the uppercase Greek letter Sigma, e.g. $\Sigma$.
* The covariance for each pair of random variables is calculated as above.
<br><br>
\begin{equation*}
\Sigma = E[(X-E[X]) \times (Y-E[Y])]
\end{equation*}
<br><br>
where, 
<br><br>
\begin{equation*}
\Sigma_{i,j} = cov(X_{i},Y_{j})
\end{equation*}
<br><br>
And $X$ is a matrix where each column represents a random variable. The covariance matrix provides a useful tool for separating the structured relationships in a matrix of random variables. This can be used to decorrelate variables or applied as a transform to other variables. It is a key element used in the Principal Component Analysis data reduction method, or PCA for short.
<br><br>
The covariance matrix can be calculated in NumPy using the $cov()$ function. By default, this function will calculate the sample covariance matrix. The $cov()$ function can be called with a single 2D array where each sub-array contains a feature (e.g. column). If this function is called with your data defined in a normal matrix format (rows then columns), then a transpose of the matrix will need to be provided to the function in order to correctly calculate the covariance of the columns. Below is an example that defines a dataset with $5$ observations across $3$ features and calculates the covariance matrix.

In [13]:
# covariance matrix
from numpy import array
from numpy import cov
# define matrix of observations
X = array([
[1, 5, 8],
[3, 5, 11],
[2, 4, 9],
[3, 6, 10],
[1, 5, 10]])
print(X)
# calculate covariance matrix
Sigma = cov(X.T)
print(Sigma)

[[ 1  5  8]
 [ 3  5 11]
 [ 2  4  9]
 [ 3  6 10]
 [ 1  5 10]]
[[1.   0.25 0.75]
 [0.25 0.5  0.25]
 [0.75 0.25 1.3 ]]
